### ISSUE TITLE
Test the current version of the API

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/table-state-rest-api#1]
@therter I have just finished configuring the service. It can be found here:

https://clarity.meteogrid.com/api/request_exposure
https://clarity.meteogrid.com/api/request_hazard

There are only two options for now. To make it work you need to do a POST request with a certain request.json file depending on the request. You can find the examples in the examples folder: https://github.com/clarity-h2020/table-state-rest-api/tree/master/examples 

I've been using the layers already available in geoserver. I'm keeping in mind what @maesbri said about a different source in the future, but I won't implement it until I have some feedback.

Note that the requests are very sensible to the bbox. I'm working on some error handling on that regard and on other possible sources of error now, but it's not yet available in the server.

The responses should look something like what you see in the same folder.

**Comment by ghilbrae** [comment]
BTW, you can check the available layers in here: https://clarity.meteogrid.com/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?3

Note that some are duplicated. This is because we are changing the workspaces  but we have not deleted the previous ones.

**Comment by therter** [comment]
I have tested the service with curl and it works fine. But to use the service within the table-component, the following response header must be set:
Access-Control-Allow-Origin: *

**Comment by ghilbrae** [comment]
I think it should work now. I've added the header and I'm getting it in my responses. Let me know if it works for you too.

**Comment by therter** [comment]
Thank you, it works for me too

**Comment by ghilbrae** [comment]
I'm closing this issue now. 
Please open new issues for bugs, questions, new functionality/options.
