### ISSUE TITLE
Submit layer URLs within the request

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/table-state-rest-api#3]
It may be needed to add a URL field to the request to determine the source of the layer.

There are a few considerations:
- All the layers of one request are stored in the same source (geoserver or whatever) => one global field in the request.
- Each layer is retrieved from a different source => a field per layer.
- The layers will always come from the same source => no need for field, handle this via API configuration.

**Comment by p-a-s-c-a-l** [comment]
not needed anymore
