### ISSUE TITLE
Additional information on HC response

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/table-state-rest-api#4]
@therter do you want to me to add the values obtained from the threshold comparison to the response so they can be added to the table?

**Comment by therter** [comment]
@ghilbrae  yes, add the values to the response, please and I will add them to the table

**Comment by ghilbrae** [comment]
Ok, I've just changed the formula for calculating the value and added the values to the response. You can check the sample response file here: https://github.com/clarity-h2020/table-state-rest-api/blob/master/examples/response.json and all the changes in commit: https://github.com/clarity-h2020/table-state-rest-api/commit/9a72f9f29627d0d0b25872cea832538d096d4382

Let me know if you find any issue or if you need me to change anything.
