### ISSUE TITLE
Units for Hazard table

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/table-state-rest-api#5]
It may be needed to add unit information to the responses for the HC layers.

The existing layers do not have that information as of now. This should be taken into account in the future to add this when generating the layers.

**Comment by RobAndGo** [comment]
For the hazard characterisation, the unit information would/should be stored within the meta-data of each climate index, e.g. for summer days, tropical nights, Tx75p, the units would be days. For other hazards involving precipitation, the units will be either days or mm of rain. 

Interestingly, when filling out the .json file for the resources in the data package, there doesn't seem to be a "unit" field.

For the hazard table which identifies the hazard level as 1,2,3 (low, medium, high), then these levels would not have units.

**Comment by maesbri** [comment]
> Interestingly, when filling out the .json file for the resources in the data package, there doesn't seem to be a "unit" field.

Indeed, there is no "uom" property defined at resource object level. However, I see 3 possibilities:
1. use the "parameters" property and define hazard index variable
"parameters": [
      { "name": "summer-days",
        "type": integer,
        "uom": "days"
}]

2. Add a new tag to the resource, e.g., "uom:days"
"tags": [
    "resource-type:hazard-index",
    ......
    "uom:days"
]

3. Add a new property "uom" in the "gridBandInfo" object

Personally, I am more in favour of options 2) or 3). The advantage of option 3) is that if the resource is a multiband grid/raster, then we can especify for each band the uom (as each band may store information of different nature).

**Comment by p-a-s-c-a-l** [comment]
obsolete
