### ISSUE TITLE
Update server with new version

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/table-state-rest-api#6]
@therter I have a newer version of the API ready but I did not want to update anything on our server just before the review.

This new version has some exception control and logging capabilities, which should not be a problem from your side. But also, I've added an EPSG field to the requests, which you'll need to consider. I'd rather you let me know when it is best for you to do this change so it does not mess up anything you might be working on.

**Comment by therter** [comment]
@ghilbrae You can do the update today

**Comment by ghilbrae** [comment]
@therter I've just updated it.

From now on, for both requests (EE & HC) you should include the epsg:
```json
     "type": "eu-gl:hazard-characterization",
    "epsg": "EPSG:3035",
    "bbox": [4466000.0, 2130000.0, 4491000.0, 2155000.0],
    "hazards": [{ ...
```

I'll monitor the issues as well as the log to see if everything works fine.
