### ISSUE TITLE
Exposure - Switch to EMIKAT API

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/table-state-rest-api#7]
Exposure Data (Population) for whole Europe will be served from a [new EMIKAT API](https://github.com/clarity-h2020/emikat/issues/10). 
This means, that the table API for aggregating Exposure Data has to be updated accordingly.
Additionally, the respective [Exposure Resources](https://github.com/clarity-h2020/data-package/issues/10) in the Data Package have to be updated as well as the [Table Component](https://github.com/clarity-h2020/table-components/issues/3#issuecomment-506718558).

@humerh Could you please provide an example request and response? To keep the changes to the table-state-rest-api minimal, it would be helpful if EMIKAT API could offer the the same API as currently used by the table-state-rest-api to access the underlying exposure data. @ghilbrae  Is it WCS, WFS, ...?

It may be necessary to parametrise the URL as described [here](). Likewise the parameters have to be supported by the table-state-rest-api. This is somehow related to https://github.com/clarity-h2020/table-state-rest-api/issues/3.

**Comment by ghilbrae** [comment]
As we used geoserver to publish the data/layers, we took advantage of its capabilities regarding OGC standards. In short, we are using WCS to access the layers and get the information needed for the tables.

**Comment by ghilbrae** [comment]
I know this is not high priority rn but if we need to switch the table API to EMIKAT I'll need info on the EMIKAT API, WCS, WMS, etc. endpoints and also a user/pass or token or whatever it is that it's needed to connect to the service. Thanks!

https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)

**Comment by humerh** [comment]
Exposure data (Population) calculated from EMIKAT:

Methode:
We use the Populationen Data from EUROSTAT (1km*1km) and split this data to the 500m-Grid by using Landcover data from Copernicus. This data are available for all Europe.

REST API: https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_EL_POPULATION_FAKE.2016/table/data?rownum=1000 

or: 

https://service.emikat.at/EmiKatTst/api/scenarios/$emikatId/feature/tab.CLY_EL_POPULATION_FAKE.2016/table/data

**Comment by p-a-s-c-a-l** [comment]
> I know this is not high priority rn but if we need to switch the table API to EMIKAT I'll need info on the EMIKAT API, WCS, WMS, etc. endpoints and also a user/pass or token or whatever it is that it's needed to connect to the service. Thanks!

Questions / Discussions regarding the EMIKAT Exposure API should continue [here](https://github.com/clarity-h2020/emikat/issues/10#issuecomment-509919538).

**Comment by p-a-s-c-a-l** [comment]
There is no WCS Endpoint, so you would need to the use [CSV endpoint](https://github.com/clarity-h2020/emikat/issues/10#issuecomment-510068266). 

CSV Format Population Exposure for Europe:

```
GRID_ID;Population 
500mE46730N19800;395.0 
500mE46730N19805;394.0 
500mE46735N19800;394.0 
500mE46735N19805;394.0 
``` 

However, for local data it look different:
```
OBJECT_ID;GRID_ID;POPULATION_LT15;POPULATION_15TO65;POPULATION_GT65
49704;500mE46735N19805;73.88189697265625;320.4410095214844;58.539100646972656
49678;500mE46735N19810;54.60070037841797;178.06399536132812;27.587299346923828
49691;500mE46735N19815;21.633699417114258;81.45919799804688;10.961799621582031
49730;500mE46735N19820;435.5150146484375;1500.4000244140625;254.0070037841797
49731;500mE46735N19825;820.666015625;3915.60009765625;640.0349731445312
49710;500mE46735N19830;726.43798828125;3172.10009765625;596.3989868164062
```
And of course for different Element at Risk Types. :hurtrealbad:

**Comment by therter** [comment]
An example response for the  table-state-rest-api can be found [here](https://github.com/clarity-h2020/table-state-rest-api/blob/master/examples/EE_response.json). The request for table-state-rest-api can be found [here](https://github.com/clarity-h2020/table-state-rest-api/blob/master/examples/EE_request.json)

**Comment by p-a-s-c-a-l** [comment]
We'll provide [Simplified Table Components](https://github.com/clarity-h2020/table-components/issues/19) until the above questions have been resolved. So putting this on hold. ATM no further modifications to the table API are needed.

**Comment by humerh** [comment]
In my opinion this is already done!!

**Comment by p-a-s-c-a-l** [comment]
@humerh Depends on where the original population Exposure is stored in EMIKAT or in Meteogrid WCS?

**Comment by p-a-s-c-a-l** [comment]
We don't need to switch to EMIKAT API since the exposure data is available on METEOROID Geoserver too.
